# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFulltestMyToDos():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fulltestMyToDos(self):
    # Test name: FulltestMyTo-Dos
    # Step # | name | target | value | comment
    # 1 | open | https://my-vue-todos.netlify.app/ |  | Open My to-dos App
    self.driver.get("https://my-vue-todos.netlify.app/")
    # 2 | waitForElementVisible | css=h1 | My to-dos | Waiting for My to-dos finish to load
    WebDriverWait(self.driver, My to-dos).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "h1")))
    # 3 | verifyText | css=h1 | My to-dos | Verify Title App
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "My to-dos"
    # 4 | verifyText | css=.d-flex:nth-child(1) > .flex-grow-1 | Do the dishes | Verify To Do List Item (Item 1)
    assert self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .flex-grow-1").text == "Do the dishes"
    # 5 | verifyText | css=.d-flex:nth-child(2) > .flex-grow-1 | Take out the trash | Verify To Do List Item (Item 2)
    assert self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(2) > .flex-grow-1").text == "Take out the trash"
    # 6 | verifyText | css=.d-flex:nth-child(3) > .flex-grow-1 | Finish doing laundry | Verify To Do List Item (Item 3)
    assert self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .flex-grow-1").text == "Finish doing laundry"
    # 7 | click | css=.d-flex:nth-child(1) > .btn-outline-primary > .fa |  | Click button Edit on To Do List Item 1
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .btn-outline-primary > .fa").click()
    # 8 | type | css=.flex-grow-1 > .form-control | Edited To Do List Item 1 | Update Text on To Do List Item 1
    self.driver.find_element(By.CSS_SELECTOR, ".flex-grow-1 > .form-control").send_keys("Edited To Do List Item 1")
    # 9 | sendKeys | css=.flex-grow-1 > .form-control | ${KEY_ENTER} | Enter Keyboard to Submit Text
    self.driver.find_element(By.CSS_SELECTOR, ".flex-grow-1 > .form-control").send_keys(Keys.ENTER)
    # 10 | click | css=.d-flex:nth-child(2) > .btn-outline-primary > .fa |  | Click button Edit on To Do List Item 2
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(2) > .btn-outline-primary > .fa").click()
    # 11 | type | css=.flex-grow-1 > .form-control | Edited To Do List Item 2 | Update Text on To Do List Item 2
    self.driver.find_element(By.CSS_SELECTOR, ".flex-grow-1 > .form-control").send_keys("Edited To Do List Item 2")
    # 12 | sendKeys | css=.flex-grow-1 > .form-control | ${KEY_ENTER} | Enter Keyboard to Submit Text
    self.driver.find_element(By.CSS_SELECTOR, ".flex-grow-1 > .form-control").send_keys(Keys.ENTER)
    # 13 | click | css=.d-flex:nth-child(3) > .btn-outline-primary |  | Click button Edit on To Do List Item 3
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .btn-outline-primary").click()
    # 14 | type | css=.flex-grow-1 > .form-control | Edited To Do List Item 3 | Update Text on To Do List Item 3
    self.driver.find_element(By.CSS_SELECTOR, ".flex-grow-1 > .form-control").send_keys("Edited To Do List Item 3")
    # 15 | sendKeys | css=.flex-grow-1 > .form-control | ${KEY_ENTER} | Enter Keyboard to Submit Text
    self.driver.find_element(By.CSS_SELECTOR, ".flex-grow-1 > .form-control").send_keys(Keys.ENTER)
    # 16 | click | css=.d-flex:nth-child(1) > .flex-grow-1 > span |  | Mark as Done (To Do List Item 1)
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .flex-grow-1 > span").click()
    # 17 | click | css=.d-flex:nth-child(2) > .flex-grow-1 > span |  | Mark as Done (To Do List Item 2)
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(2) > .flex-grow-1 > span").click()
    # 18 | click | css=.d-flex:nth-child(3) > .flex-grow-1 |  | Mark as Done (To Do List Item 3)
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .flex-grow-1").click()
    # 19 | click | css=.d-flex:nth-child(1) > .flex-grow-1 > span |  | Mark as Undone (To Do List Item 1)
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .flex-grow-1 > span").click()
    # 20 | click | css=.d-flex:nth-child(2) > .flex-grow-1 > span |  | Mark as Undone (To Do List Item 2)
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(2) > .flex-grow-1 > span").click()
    # 21 | click | css=.completed > span |  | Mark as Undone (To Do List Item 3)
    self.driver.find_element(By.CSS_SELECTOR, ".completed > span").click()
    # 22 | click | css=.form-control |  | Click Textbox "create a new to do"
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").click()
    # 23 | type | css=.form-control | This is created new item | Input text on textbox "create a new to do"
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("This is created new item")
    # 24 | sendKeys | css=.form-control | ${KEY_ENTER} | Enter Keyboard to Submit Text
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys(Keys.ENTER)
    # 25 | verifyText | css=.d-flex:nth-child(4) > .flex-grow-1 > span | This is created new item | Verify created new item
    assert self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(4) > .flex-grow-1 > span").text == "This is created new item"
    # 26 | click | css=.form-control |  | Click Textbox "create a new to do"
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").click()
    # 27 | type | css=.form-control | ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ | Input text on textbox with long char
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ")
    # 28 | sendKeys | css=.form-control | ${KEY_ENTER} | Enter Keyboard to Submit Text
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys(Keys.ENTER)
    # 29 | verifyText | css=.d-flex:nth-child(5) > .flex-grow-1 > span | ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ | Verify created new item with long char
    assert self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) > .flex-grow-1 > span").text == "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ"
    # 30 | click | css=.d-flex:nth-child(5) > .btn-outline-danger > .fa |  | Deleted To Do List Item 5
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) > .btn-outline-danger > .fa").click()
    # 31 | click | css=.d-flex:nth-child(4) > .btn-outline-danger > .fa |  | Deleted To Do List Item 4
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(4) > .btn-outline-danger > .fa").click()
    # 32 | click | css=.d-flex:nth-child(3) > .btn-outline-danger > .fa |  | Deleted To Do List Item 3
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(3) > .btn-outline-danger > .fa").click()
    # 33 | click | css=.d-flex:nth-child(2) > .btn-outline-danger > .fa |  | Deleted To Do List Item 2
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(2) > .btn-outline-danger > .fa").click()
    # 34 | click | css=.fa-trash |  | Deleted To Do List Item 1
    self.driver.find_element(By.CSS_SELECTOR, ".fa-trash").click()
    # 35 | close |  |  | Close Browser
    self.driver.close()
  
